name: Build and Deploy on Dev

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build_and_deploy_angular:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install or Update packages
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build DSP Application
      run: |
        npm install
        npm run build
        
    - name: Deploy DS Portal on IIS      
      run: |
        xcopy /s /y dist\my-app\* C:\inetpub\wwwroot\CICD  
  
    - name: Move to API Directory
      run: cd api\api                

  build_and_deploy_api:
    runs-on: self-hosted
    
    steps:
    - name: Build API - Restore dependency
      run: dotnet restore

    - name: Build API - Build API
      run: dotnet build --no-restore
