name: Build and Deploy on Dev

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Pull app from Github
    - uses: actions/checkout@v3

    - name: Install/Update packages
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build DSP Application
      run: |
        npm install
        npm run build
        
    - name: Deploy DS Portal to IIS      
      run: |
        xcopy /s /y dist\my-app\* C:\inetpub\wwwroot\CICD
